# Generated by Django 5.2.8 on 2025-12-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'is_active'], name='hotels_hote_city_a8c2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price_per_night'], name='hotels_hote_price_p_7002d9_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-created_at'], name='hotels_hote_created_93df5c_idx'),
        ),
    ]
