# Generated by Django 5.2.8 on 2025-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_city_alter_hotel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Image encodée en base64 (data:image/jpeg;base64,...)', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_size',
            field=models.IntegerField(default=0, help_text='Taille en bytes'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_type',
            field=models.CharField(blank=True, choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('webp', 'WebP'), ('svg', 'SVG')], default='jpeg', max_length=50, null=True),
        ),
    ]
